export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";

export const GET_PRODUCT = "GET_PRODUCT";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";

export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAILED = "EDIT_PRODUCT_FAILED";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";


// export const GET_USERS = "GET_USERS";
// export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
// export const GET_USERS_FAILED = "GET_USERS_FAILED";

// export const GET_USER = "GET_USER";

// export const ADD_USER = "ADD_USER";
// export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
// export const ADD_USER_FAILED = "ADD_USER_FAILED";

// export const EDIT_USER = "EDIT_USER";
// export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
// export const EDIT_USER_FAILED = "EDIT_USER_FAILED";

// export const DELETE_USER = "DELETE_USER";
// export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
// export const DELETE_USER_FAILED = "DELETE_USER_FAILED";